import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import { fonts } from '../configs/fonts'
import Providers from './_providers'

import '~/assets/styles/global/index.scss'

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className={fonts.assistantFont.className}>
      <Providers>{children}</Providers>
    </body>
  </html>
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default RootLayout
