import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import '~/assets/styles/global.css'
import Providers from './_providers'

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body>
      <Providers>{children}</Providers>
    </body>
  </html>
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default RootLayout
