import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import { Toaster } from 'sonner'
import '~/assets/styles/global/index.scss'
import { fonts } from '../configs/fonts'
import Providers from './_providers'

const RootLayout = ({ children }: PropsWithChildren) => (
  <html lang="en">
    <body className={fonts.assistantFont.className}>
      <Providers>{children}</Providers>
      <Toaster richColors duration={5000} position="top-right" />
    </body>
  </html>
)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default RootLayout
